version: '3.8'

services:
  app:
    build: .
    container_name: go_qr
    working_dir: /app
    volumes:
      - .:/app
    ports:
      - "8080:8080"
    environment:
      - GO111MODULE=on
      - CGO_ENABLED=0
      - API-KEY=test
    networks:
      - go-network

networks:
  go-network:
    driver: bridge
